version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - ./db:/db
    env_file:
      - ./env/.env
    networks:
      - fastapi_network
    restart: always

networks:
  fastapi_network:
    driver: bridge
